In [259]:
# read csv file into a list of lists
import csv
def read_data(filename):
    footballTable = list()
    reader = csv.reader(open(filename))
    next(reader)
    for row in reader:
        footballTable.append(row)
        
    diff_list = []
    for item in footballTable:
        diff_list.append(abs(int(item[5])-int(item[6])))
   
    index_value = diff_list.index(min(diff_list)) # find index with minimum diff
    
    for item in footballTable:
        get_name = footballTable[index_value][0] # get team name with minium diff
        
    return get_name
    

In [260]:
read_data("football.csv")

'Aston_Villa'

In [354]:
def degrees(filename):
    import csv
    file = open(filename)
    csv_f = csv.reader(file)
    
    # Creating a list to store all the degrees from the csv file
    degree_list = []
    
    # Creating an empty dictionary for counting the frequency
    degree_count = {}
    
    next(csv_f) #skip the first row
    
    for row in csv_f:
        #removing white space
        degree_list.append()
        
    
    print(degree_list)
    
    return degree_list

In [355]:
degrees("faculty.csv")

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [344]:
import csv

def count_degrees(filename):
    file = open(filename)
    csv_f = csv.reader(file)
    
    # Creating a list to store all the degrees from the csv file
    degree_list = []
    
    # Creating an empty dictionary for counting the frequency
    degree_count = {}
    
    next(csv_f) #skip the first row
    
    for row in csv_f:
        #removing white spaces
        
        clean_1= row[1].strip() 
        degree_list.append(clean_1)
    
    #removing period to standarize the degree notation
    degree_list = [x.replace('.','') for x in degree_list] 
    new_degree_list = [degree for degrees in degree_list for degree in degrees.split()]
    
    #count degree frequency
    for degree in new_degree_list:
        degree_count[degree] = degree_count.get(degree,0)+1
    
    return degree_count

In [345]:
count_degrees("faculty.csv")

TypeError: append() takes exactly one argument (0 given)

In [283]:
#get title count
import csv

def count_titles(csv_file_name):
    file = open(csv_file_name)
    csv_f = csv.reader(file)
    
    # Creating a list to store all the titles from the csv file
    title_list = []
    # Creating an empty dictionary for counting the frequency
    title_count = {}
    
    next(csv_f) #skip the first row
    
    for row in csv_f:
        title_list.append(row[2])
        
    #take only the first word of strings in the list
    new_title_list = [title.split()[0] for title in title_list]
    
    #count title frequency
    for title in new_title_list:
        title_count[title] = title_count.get(title,0)+1
        
    return title_count
    

In [284]:
count_titles("faculty.csv")

{'Associate': 12, 'Professor': 13, 'Assistant': 12}

In [286]:
#deleting word after space
l= ['dif aye','wat sc d', 'pub on']
[title.split()[0] for title in l]

['dif', 'wat', 'pub']

In [321]:
#get email
import csv

def emails(csv_file_name):
    file = open(csv_file_name)
    csv_f = csv.reader(file)
    
    # Creating a list to store all the titles from the csv file
    email_list = []
   
    next(csv_f) #skip the first row
    
    for row in csv_f:
        email_list.append(row[3])
    
    
      
    return email_list

In [322]:
emails("faculty.csv")

['bellamys@mail.med.upenn.edu',
 'warren@upenn.edu',
 'bryanma@upenn.edu',
 'jinboche@upenn.edu',
 'sellenbe@upenn.edu',
 'jellenbe@mail.med.upenn.edu',
 'ruifeng@upenn.edu',
 'bcfrench@mail.med.upenn.edu',
 'pgimotty@upenn.edu',
 'wguo@mail.med.upenn.edu',
 'hsu9@mail.med.upenn.edu',
 'rhubb@mail.med.upenn.edu',
 'whwang@mail.med.upenn.edu',
 'mjoffe@mail.med.upenn.edu',
 'jrlandis@mail.med.upenn.edu',
 'liy3@email.chop.edu',
 'mingyao@mail.med.upenn.edu',
 'hongzhe@upenn.edu',
 'rlocalio@upenn.edu',
 'nanditam@mail.med.upenn.edu',
 'knashawn@mail.med.upenn.edu',
 'propert@mail.med.upenn.edu',
 'mputt@mail.med.upenn.edu',
 'sratclif@upenn.edu',
 'michross@upenn.edu',
 'jaroy@mail.med.upenn.edu',
 'msammel@cceb.med.upenn.edu',
 'shawp@upenn.edu',
 'rshi@mail.med.upenn.edu',
 'hshou@mail.med.upenn.edu',
 'jshults@mail.med.upenn.edu',
 'alisaste@mail.med.upenn.edu',
 'atroxel@mail.med.upenn.edu',
 'rxiao@mail.med.upenn.edu',
 'sxie@mail.med.upenn.edu',
 'dxie@upenn.edu',
 'weiyang@mail.m

In [325]:
#given email list, get unique domains


def unique_domains(email):
    
    #domain name after @
    domain_list = [i.split("@",1)[1] for i in email]
    
    #fine unique domain names
    unique_set= set(domain_list)
    unique_list = list(unique_set)
      
    return unique_list

In [326]:
unique_domains(['bellamys@mail.med.upenn.edu',
 'warren@upenn.edu',
 'bryanma@upenn.edu',
 'jinboche@upenn.edu',
 'sellenbe@upenn.edu',
 'jellenbe@mail.med.upenn.edu',
 'ruifeng@upenn.edu',
 'bcfrench@mail.med.upenn.edu',
 'pgimotty@upenn.edu',
 'wguo@mail.med.upenn.edu',
 'hsu9@mail.med.upenn.edu',
 'rhubb@mail.med.upenn.edu',
 'whwang@mail.med.upenn.edu',
 'mjoffe@mail.med.upenn.edu',
 'jrlandis@mail.med.upenn.edu',
 'liy3@email.chop.edu',
 'mingyao@mail.med.upenn.edu',
 'hongzhe@upenn.edu',
 'rlocalio@upenn.edu',
 'nanditam@mail.med.upenn.edu',
 'knashawn@mail.med.upenn.edu',
 'propert@mail.med.upenn.edu',
 'mputt@mail.med.upenn.edu',
 'sratclif@upenn.edu',
 'michross@upenn.edu',
 'jaroy@mail.med.upenn.edu',
 'msammel@cceb.med.upenn.edu',
 'shawp@upenn.edu',
 'rshi@mail.med.upenn.edu',
 'hshou@mail.med.upenn.edu',
 'jshults@mail.med.upenn.edu',
 'alisaste@mail.med.upenn.edu',
 'atroxel@mail.med.upenn.edu',
 'rxiao@mail.med.upenn.edu',
 'sxie@mail.med.upenn.edu',
 'dxie@upenn.edu',
 'weiyang@mail.med.upenn.edu'])

['cceb.med.upenn.edu', 'mail.med.upenn.edu', 'email.chop.edu', 'upenn.edu']

In [338]:
import csv

def write_to_csv(list_of_emails):

    with open('emails.csv','w') as new_file:
        csv_writer = csv.writer(new_file)
        
        csv_writer.writerow('Email List')

        for email in list_of_emails:
            csv_writer.writerow(email)
    return 

In [339]:
write_to_csv(["hello",'what','yes'])

In [153]:
#create dict from csv with key = last name
def get_dict1():
    import csv
    with open ('faculty.csv','r') as csv_file:
        csv_reader = csv.reader(csv_file)
        
        people = {}
        fullname = []
        #skip the first row
        next(csv_reader)
        
        for row in csv_reader:
           #get the full name
            fullname.append(row[0])
            #get the last name from full name
            lastname_list = list(map(lambda name: name.split()[-1], fullname))
            
            
    return people
                
            
      


In [155]:
get_dict1()

{'Bellamy': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Bilker': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Bryan': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Chen': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Ellenberg': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Feng': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'French': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Gimotty': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Guo': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Hsu': [' Ph.D.',
  'Assistant Professor of Biostatistics',
  'weiyang@mail.med.upenn.edu'],
 'Hubbard': [' Ph.D.',
  'Assistant 

In [282]:
#create dict from csv with key = last name
def get_dict():
    import csv
    with open ('faculty.csv','r') as csv_file:
        csv_reader = csv.reader(csv_file)
        
        faculty_list= {}
        lastname= []
        fullname = []
        #skip the first row
        next(csv_reader)
    
        #loop to read out names as key and the rest as values
        #perform split() to only get the last name
        for name, *values in csv_reader:
            faculty_list.update({map(lambda name:name.split()[-1],name):list(values)})

    return faculty_list
                

In [283]:
get_dict()

{<map at 0x10d217a90>: [' Sc.D.',
  'Associate Professor of Biostatistics',
  'bellamys@mail.med.upenn.edu'],
 <map at 0x10d1f5b90>: ['Ph.D.',
  'Professor of Biostatistics',
  'warren@upenn.edu'],
 <map at 0x10d1f50d0>: [' PhD',
  'Assistant Professor of Biostatistics',
  'bryanma@upenn.edu'],
 <map at 0x10d1fb850>: [' Ph.D.',
  'Associate Professor of Biostatistics',
  'jinboche@upenn.edu'],
 <map at 0x10d1fb450>: [' Ph.D.',
  'Professor of Biostatistics',
  'sellenbe@upenn.edu'],
 <map at 0x10d1fb290>: [' Ph.D.',
  'Professor of Biostatistics',
  'jellenbe@mail.med.upenn.edu'],
 <map at 0x10d1fb710>: [' Ph.D',
  'Assistant Professor of Biostatistics',
  'ruifeng@upenn.edu'],
 <map at 0x10d1fb2d0>: [' PhD',
  'Associate Professor of Biostatistics',
  'bcfrench@mail.med.upenn.edu'],
 <map at 0x10d216350>: [' Ph.D',
  'Professor of Biostatistics',
  'pgimotty@upenn.edu'],
 <map at 0x10d216890>: [' Ph.D',
  'Professor of Biostatistics',
  'wguo@mail.med.upenn.edu'],
 <map at 0x10d216310

In [277]:
#read csv file and get key as tuple and its correspoinding values in list
def get_dict2():
    import csv
    faculty_dict={}
    
    with open('faculty.csv') as file:
        csv_reader = csv.reader(file)
        next(csv_reader)
        for name, *values in csv_reader:
             faculty_dict.update({tuple(map(str,name.split(' '))):list(values)})
           
    return faculty_dict



In [74]:
get_dict2()

{('Scarlett', 'L.', 'Bellamy'): [' Sc.D.',
  'Associate Professor of Biostatistics',
  'bellamys@mail.med.upenn.edu'],
 ('Warren', 'B.', 'Bilker'): ['Ph.D.',
  'Professor of Biostatistics',
  'warren@upenn.edu'],
 ('Matthew', 'W', 'Bryan'): [' PhD',
  'Assistant Professor of Biostatistics',
  'bryanma@upenn.edu'],
 ('Jinbo', 'Chen'): [' Ph.D.',
  'Associate Professor of Biostatistics',
  'jinboche@upenn.edu'],
 ('Susan', 'S', 'Ellenberg'): [' Ph.D.',
  'Professor of Biostatistics',
  'sellenbe@upenn.edu'],
 ('Jonas', 'H.', 'Ellenberg'): [' Ph.D.',
  'Professor of Biostatistics',
  'jellenbe@mail.med.upenn.edu'],
 ('Rui', 'Feng'): [' Ph.D',
  'Assistant Professor of Biostatistics',
  'ruifeng@upenn.edu'],
 ('Benjamin', 'C.', 'French'): [' PhD',
  'Associate Professor of Biostatistics',
  'bcfrench@mail.med.upenn.edu'],
 ('Phyllis', 'A.', 'Gimotty'): [' Ph.D',
  'Professor of Biostatistics',
  'pgimotty@upenn.edu'],
 ('Wensheng', 'Guo'): [' Ph.D',
  'Professor of Biostatistics',
  'wguo@

In [72]:
# split full name to first and last

full = "jOhn m. wht"
first,last = full.split(" ",1)
print(last)

m. wht


In [66]:
#map lambda funciton to get last name from a list of full names
full = ['a b','c e d','e f']
last = list(map(lambda name: name.split()[-1], full))
print(last)

['b', 'd', 'f']


In [69]:
#splite full name into first and last (choose how the name is split)
name = "John F. Kennedy"
*first,last = name.split()
print(first)
print(last)

['John', 'F.']
Kennedy


In [141]:
#create dict from csv with key = last name
def dicttest():
    import csv
    with open ('faculty.csv','r') as csv_file:
        csv_reader = csv.DictR\\\eader(csv_file)
        
        people = {}
        fullname = []
        degree= []
        title = []
        email = []
        values = []
        #skip the first row
        next(csv_reader)
        
        for row in csv_reader:
            row = values#get list of full name
            
            print(values)
            fullname.append(row[0])
            
            
            #get the last name from full name
            lastname = list(map(lambda name: name.split()[-1], fullname))
            
            
            
    return


In [262]:
import numpy as np
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [264]:
B.shape

(2, 2)

In [265]:
u.shape

(4,)

In [266]:
np.dot(u,v)

51

In [267]:
u+v

array([ 9,  7, -4,  9])

In [268]:
np.linalg.norm(u)

8.602325267042627

In [271]:
A-C.T

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [272]:
C.T + 3*D

array([[14,  3,  3],
       [ 2,  7,  9]])

In [309]:
def cal_matrix(mtrx1,mtrx2):
    try:
        print(mtrx1*mtrx2)
    except ValueError:
        print(None)

In [311]:
cal_matrix(A,D)

[[ 3 -4 -3]
 [ 2 14 12]]


In [278]:
B*A.T

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [279]:
B*C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [280]:
C*B

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [286]:
np.power(B,4)

array([[1, 1],
       [0, 1]])

In [283]:
A*A.T

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [284]:
D.T*D

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [287]:
A+C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [288]:
dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}

In [289]:
print(dimensions)

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}


In [290]:
alpha = 6

u_plus_v = u+v            # u+v
u_minus_v = u-v           # u-v
alpha_times_u = alpha*u    # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)             # u . v
norm_u =  np.linalg.norm(u)

In [291]:
print(u_plus_v)

[ 9  7 -4  9]


In [292]:
print(u_dot_v)

51
